### ISSUE TITLE
新版本kot在windows和linux系统下怎么跑起来呢？

### ISSUE THREAD

**Issue by Winter95** [Acmesec/CTFCrackTools#28]

**Comment by Winter95** [comment]
以前的版本有jar包，现在没有了，可以麻烦在readme里面添加教程吗？万分感谢！

**Comment by 0Chencc** [comment]
一直有jar包的，https://github.com/Acmesec/CTFCrackTools/releases/tag/3.2.4
下载一下这个版本，然后解压就有了
