### ISSUE TITLE
无法正常显示

### ISSUE THREAD

**Issue by tyfhxn** [Acmesec/CTFCrackTools#30]
在Windows 10 专业版   操作系统内部版本：19042.804    下打开jar文件，会出现无法完全显示的状况，最上面一行的菜单栏一直出不来
![image](https://user-images.githubusercontent.com/58685206/107910714-e9e76b80-6f95-11eb-989c-4b6808b476db.png)
![image](https://user-images.githubusercontent.com/58685206/107910754-f966b480-6f95-11eb-8f04-1a562ecb6500.png)

**Comment by 0Chencc** [comment]
这个问题是本身支持这个ui的外观包不支持java8以上的版本。我下个版本就会移除这个包。

**Comment by tyfhxn** [comment]
> 这个问题是本身支持这个ui的外观包不支持java8以上的版本。我下个版本就会移除这个包。

**Comment by tyfhxn** [comment]
原来如此，谢谢你的回答，帮我解决了问题
