### ISSUE TITLE
初次添加插件，重复在popup menu处添加

### ISSUE THREAD

**Issue by euzenlee** [Acmesec/CTFCrackTools#33]
新增的插件菜单都跑到opoup menu那里了，Top menu处是空白的，再次打开程序会正常。

TaddPlugins.addActionListener {} 里，下面代码有手误：
when (json.search(title,"type")) {
    "crypto" -> {
        **Plugins.add(buildPluginMenuItem(title))
        _Plugins.add(buildPluginMenuItem(title))_**
    }
}

第二个Plugins应该是TPlugins才对。

**Comment by 0Chencc** [comment]
好的，我修改一下代码。感谢！

**Comment by euzenlee** [comment]
> 
> 
> 好的，我修改一下代码。感谢！

这工具做得非常不错。自己写了不少插件放在里面，可以减少其他小工具的调用，大为方便。但随着插件增加，菜单方面的缺点就慢慢呈现，没有二、三级菜单分类，所有插件混在一起，查找和分类都不便，如果以后版本可以增加这方面功能就好了。
另外，插件的参数弹出窗口，只有字符输入，即使可以多个字段，也显得有些不足，如果增加下拉选择之类的弹出，就更加完美了。

**Comment by 0Chencc** [comment]
收到，我这几天抽个时间准备开始重构。
